include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    unnecessary_null_comparison: error
    invalid_annotation_target: ignore

linter:
  rules:
    camel_case_types: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    file_names: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
